### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by dan-kez** [kirankumbhar/File-Transfer-FTP-to-S3-Python#1]
Hello! 

I was reading though your blog post and noticed that your repo is missing a license. You may wish to add one so others can expand on your work , reference it.

**Comment by kirankumbhar** [comment]
#2  Added MIT license.
Thanks for raising this!

**Comment by dan-kez** [comment]
Awesome - Thank you!

If you're interested, I ended up drawing on your work in a separate project here https://github.com/dan-kez/lambda-ftp-to-gsheet-transform . I'll likely write a small post about it sometime soon. Fun playing a bit with lambdas.

**Comment by kirankumbhar** [comment]
@dan-kez Awesome. happy to see someone found my work useful in their project! Starred you repo!
